# Generated by Django 4.2.1 on 2023-05-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnualData",
            fields=[
                ("api_number", models.IntegerField()),
                (
                    "well",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("oil", models.IntegerField()),
                ("gas", models.IntegerField()),
                ("brine", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Annual Data",
                "ordering": ["well"],
            },
        ),
    ]
